include_keywords:
  - assembly
  - TAMP
  - planning
  - embodied ai
  - embodied intelligence
  - robot manipulation
  - manipulation
  - robot grasping
  - dexterous manipulation
  - vision-language-action
  - vla
  - policy learning
  - imitation learning
  - diffusion policy
  - mobile manipulation
  - long-horizon manipulation
  - robot sim2real
  - robot learning
  - robot assemble
  - robot construction
  - robot skill learning
  - automated construction
  - robot fabrication
  - policy learning
  - long-horizon manipulation
  - assembly planning
  - trajectory prediction
  - trajectory planning
  - skill chaining
  - action model
  - world model
exclude_keywords:
  - autonomous driving
  - medical imaging
  - networking
  - non-robotic control
  - slam-only
  - pure slam
  - llm-only
  - language model only
